trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  # - task: JavaToolInstaller@0
  #   inputs:
  #     versionSpec: '11'
  #     jdkArchitecture: 'x64'
  #     jdkSource: 'PreInstalled'

  # - checkout: self

  - script: |
      javac javatest.java
      java javatest
    displayName: 'Compile and Run Java Program'
