version: 2.1
jobs:
  build:
    docker:
      - image: cimg/java:17  # Ensure this is the correct image tag
    steps:
      - checkout  # Pulls your code from the repository
      - run:
          name: Compile Java Program
          command: javac javatest.java  # Compile the Java file
      - run:
          name: Run Java Program
          command: java javatest   # Run the compiled Java class file
workflows:
  version: 2
  build:
    jobs:
      - build
