# version: 2.1
# jobs: 
#   build:
#     docker:
#       - image: alpine:latest  
#     steps:
#       - checkout
#       - run:
#           name: Install Java and Compile Java Program
#           command: |
#             apk update
#             apk add openjdk8
#             javac javatest.java
#       - run:
#           name: Run Java Program
#           command: java javatest
# workflows:
#   version: 2
#   build:
#     jobs:
#       - build





version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: aman706080/container-runner
    steps:
      - run: echo "Hi I'm on Runners!"
