version: 2.1
jobs:
  build:
    docker:
      - image: cimg/circleci/java  # Update this line
    steps:
      - checkout
      - run:
          name: Compile Java Program
          command: javac javatest.java
      - run:
          name: Run Java Program
          command: java javatest
workflows:
  version: 2
  build:
    jobs:
      - build
